### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by CPCer** [tisyang/kaos#1]
主要是感谢啦，但是一定是我太菜。。加载之后重启也不显示。。于是卸了……
https://simbled-google-pinyin.googlecode.com/files/Google%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9F%AD%E8%AF%AD%E8%A1%A8%E8%AF%B7%E5%8C%852.0.0.dis
现在用的这个。

**Comment by tisyang** [comment]
@skepts 请确保谷歌输入法中没有其他『除系统扩展』外的扩展。由于不明原因，谷歌输入法中只能启用一个Trigger类的扩展。
下载 kaos.lua，添加扩展后，切换一下输入法就可以激活了，建议再试试看。
